name: Google Closure Compiler

on:
  workflow_dispatch:
  push:
    paths: [ '**.js' ]
  pull_request:
    paths: [ '**.js' ]

jobs:
  GoogleClosureCompiler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install closure compiler
        run:  npm i -g google-closure-compiler
      - name: Run Javascript syntax check on .js files
        run:  find . -type f -iname "*.js" -print0 | xargs -0 -n1 google-closure-compiler --checks_only --language_in STABLE --warning_level VERBOSE --externs "/usr/local/lib/node_modules/google-closure-compiler/contrib/externs/jquery-3.3.js" --js
