name: PHP Syntax Checker

on:
  workflow_dispatch:
  push:
    paths: [ '**.php' ]
  pull_request:
    paths: [ '**.php' ]

jobs:
  PHPSyntaxChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run php syntax check on .php files
        run:  find . -type f -iname "*.php" -print0 | xargs -0 -n1 php --syntax-check
