name: Collect system information on runner

on:
  workflow_dispatch:
jobs:
  InspectRunner:
    runs-on: ubuntu-20.04
    steps:
      - name: List installed packages
        run:  apt list --installed
      - name: Show disk usage overview
        run:  df -h
      - name: Show disk usage on /opt
        run:  du -a -h -d 1 /opt | sort -h -r
      - name: Show disk usage on /usr
        run:  du -a -h -d 1 /usr /usr/lib /usr/local/lib /usr/local/share /usr/share | sort -h -r
