name: Spacesaver

on:
  workflow_dispatch:
jobs:
  InspectRunner:
    runs-on: ubuntu-20.04
    steps:
      - name: Uninstall some packages
        run:  sudo apt-get update;
              sudo apt-get remove --purge --autoremove --yes \
              dotnet* mono* libmono* \
              azure* google-cloud* \
              microsoft-edge* google-chrome* firefox \
              mongodb* mysql* libmysql* \
              mono* google-cloud* temurin* \
              libruby* ruby* php7* php8* llvm* libllvm* clang* libclang* hhvm;
              sudo apt-get clean
      - name: Installed packages
        run:  apt list --installed
      - name: Package size overview
        run:  dpkg-query -Wf '${Installed-size;9}\t${Package}\t${db:Status-Abbrev}\n' | grep -E 'ii $' | cut -f-2 | sort -rn
      - name: Disk usage overview
        run:  df -h
      - name: Disk usage details
        run:  for dir in /opt /usr /usr/lib /usr/local/lib /usr/local/share /usr/share; do du -ahd 1 ${dir}; done | sort -hru
