name: Stylelint

on:
  workflow_dispatch:
  push:
    paths: [ '**.css', '**.less' ]
  pull_request:
    paths: [ '**.css', '**.less' ]

jobs:
  Stylelint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install Stylelint
        run:  npm install stylelint stylelint-config-standard
      - name: Run Stylelint on .css and .less files
        run:  npx stylelint "**/*.{css,less}"
